### ISSUE TITLE
Consider requiring `class-rgba-customizer-control` in `customizer-settings.php` 

### ISSUE THREAD

**Issue by christophherr** [seothemes/child-theme-library#7]
The file/class is only used in the Customizer. 
Loading it in `settings()`, would prevent loading it unnecessaryly , saving a tiny little bit of memory and namespacing the class should be easier.

I know you are following the Genesis folder structure but adding the class to` /admin` or a customizer folder with the other two files seems more intuitive. 🤷‍♂️ 

On a side note, the Customizer `body` background-color doesn't work in the starter theme because it is overwritten by `.site-container`.

**Comment by seothemes** [comment]
Right now it’s only loaded when called using the spl_autoload_register so there’s no need to require it anywhere.

Definitely agree about the folder structure, never liked using the `classes/` directory. I’m planning on reorganizing everything into a more common structure based on https://github.com/php-pds/skeleton. This will make it easier when adding tests etc.

Regarding the RGBA control, this will be converted into a separate composer package and removed from the library. This also applies to the TGMPA class.

**Comment by seothemes** [comment]
Closed in #9. Decided to remove it entirely.

For future reference, the separate package can be found here - https://github.com/seothemes/rgba-customizer-control.

Also, the Customizer background issue has been fixed in https://github.com/seothemes/genesis-starter-theme/pull/18

**Comment by christophherr** [comment]
Looks great!
